language: java
jdk:
  - oraclejdk8
branches:
  only:
  - master

cache:
  directories:
  - $HOME/.m2

install: true
sudo: false
script: "mvn clean install"

after_success:
  - mvn -P coveralls-report cobertura:cobertura coveralls:report
